apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: auth-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: guest
        - name: RABBITMQ_PASSWORD
          value: guest
        - name: PRIVATE_KEY
          value: /etc/auth-keys/private_key
        - name: PUBLIC_KEY
          value: /etc/auth-keys/public_key
        volumeMounts:
        - name: auth-keys-volume
          mountPath: /etc/auth-keys
          readOnly: true
      volumes:
      - name: auth-keys-volume
        secret:
          secretName: auth-keys