name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: |
        chmod +x build-all.sh
        ./build-all.sh

    - name: Set up Kubernetes
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
        kubectl cluster-info
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f helm/ --validate=false
        kubectl get pods
        kubectl get services