name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: |
        chmod +x build-all.sh
        ./build-all.sh

    # Choose ONE of these approaches - not both
    # APPROACH 1: Create fresh Minikube cluster (recommended for testing)
    - name: Set up Minikube
      run: |
        # Install Minikube
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        
        # Start cluster
        minikube start --driver=docker
        minikube update-context
        
        # Verify
        kubectl cluster-info
        kubectl get nodes

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f helm/ --validate=false
        kubectl get pods
        kubectl get services
        kubectl get ingress